### PR TITLE
Remove classification worker

### PR DESCRIPTION
**Pull request by michael-bryson**
Some further work is required to remove the handlers for classification and elasticsearch classification.

 I have removed the main module and some other references to classification worker, this builds locally and the dev build is here:
http://sou-jenkins2.hpeswlab.net/job/CAFDataProcessing/view/Developer/job/CAFDataProcessing~worker-policy~remove_classification_worker~CI/

### CODE REVIEW

**Review by dermot-hardy — COMMENTED** [review]
Good so far.

**Comment by michael-bryson** [comment]
@dermot-hardy I think this is now good to go, the dev build is passing and all tests passing. I can see that the worker-classification is not being pushed to dockerhub cafinternal. The worker-classification, classification handers and converters have been removed. I also had to remove the worker-policy-handlers-converters-testing project as the tests all used the classification api. I also had to remove a number of classification tests from the worker-policy-testing project.

**Review by dermot-hardy — APPROVED** [review]

**Review by mmaBel — COMMENTED** [review]
I think these classification queue properties can be removed
https://github.com/CAFDataProcessing/worker-policy/blob/remove_classification_worker/worker-policy-testing/src/main/java/com/github/cafdataprocessing/worker/policy/testing/shared/BaseTestsHelper.java#L74

**Comment by mmaBel** [comment]
Are we going to update data-processing-service and worker-data-processing-internal database containers to not install a database for classification?

The [worker-data-processing-internal](https://github.houston.softwaregrp.net/caf/worker-data-processing-internal) stands up a classification worker (old policy version) for testing. That should be removed in a different pull request.

**Comment by dermot-hardy** [comment]
We probably should.  It would be confusing for the database to stick around.

**Comment by michael-bryson** [comment]
@dermot-hardy @mmaBel I am in the process of removing the database from the container as part of removing classification from data-processing-service and worker-data-processing-internal repositories.

**Comment by michael-bryson** [comment]
@mmaBel Re: classification queue properties, I think you are correct. I have removed these and running a debv build now.

**Comment by michael-bryson** [comment]
Dev build has passed after removing the unrequired classification queue properties.

**Review by dermot-hardy — APPROVED** [review]

**Review by mmaBel — APPROVED** [review]

**Pull request merged**
